apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w9a9jme1v-go
  janus-idp.io/tekton: w9a9jme1v-go
  backstage.io/kubernetes-id: w9a9jme1v-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w9a9jme1v-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
